# headers and icon 
title: Zhang Jia-Qi
info: PhD in CS&T'25 @ buaa # Computer Science and Technology
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
